import type { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';
import * as bcrypt from 'bcrypt';

export async function seed(knex: Knex): Promise<void> {
  await knex('users').del();

  const hashedPassword = await bcrypt.hash('Test@1234', 10);

  await knex('users').insert([
    {
      id: uuidv4(),
      nome: 'João Silva',
      email: 'joao.silva@example.com',
      password: hashedPassword,
      rua: 'Rua das Flores',
      numero: '123',
      bairro: 'Centro',
      complemento: 'Apto 101',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01310-100',
      status: 'ativo',
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      nome: 'Maria Santos',
      email: 'maria.santos@example.com',
      password: hashedPassword,
      rua: 'Avenida Paulista',
      numero: '1000',
      bairro: 'Bela Vista',
      complemento: 'Sala 500',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01311-100',
      status: 'ativo',
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      nome: 'Pedro Oliveira',
      email: 'pedro.oliveira@example.com',
      password: hashedPassword,
      rua: 'Rua Augusta',
      numero: '2500',
      bairro: 'Consolação',
      complemento: null,
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01305-100',
      status: 'ativo',
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      nome: 'Ana Costa',
      email: 'ana.costa@example.com',
      password: hashedPassword,
      rua: 'Rua Oscar Freire',
      numero: '500',
      bairro: 'Cerqueira César',
      complemento: 'Apto 1001',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01426-100',
      status: 'inativo',
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      nome: 'Carlos Mendes',
      email: 'carlos.mendes@example.com',
      password: hashedPassword,
      rua: 'Rua Haddock Lobo',
      numero: '300',
      bairro: 'Cerqueira César',
      complemento: null,
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01414-010',
      status: 'ativo',
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
  ]);
}

