import type { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';

const USER_IDS = [
  '550e8400-e29b-41d4-a716-446655440001',
  '550e8400-e29b-41d4-a716-446655440002',
  '550e8400-e29b-41d4-a716-446655440003',
  '550e8400-e29b-41d4-a716-446655440004',
  '550e8400-e29b-41d4-a716-446655440005',
];

export async function seed(knex: Knex): Promise<void> {
  await knex('finances').del();

  await knex('finances').insert([
    {
      id: uuidv4(),
      user_id: USER_IDS[0],
      valor: 1500.5,
      descricao: 'Salário mensal',
      categoria: 'Renda',
      tipo: 'receita',
      status: 'confirmada',
      data_transacao: new Date(),
      data_pagamento: new Date(),
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      user_id: USER_IDS[0],
      valor: 250.0,
      descricao: 'Pagamento de conta de luz',
      categoria: 'Utilidades',
      tipo: 'despesa',
      status: 'confirmada',
      data_transacao: new Date(),
      data_pagamento: new Date(),
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      user_id: USER_IDS[1],
      valor: 3000.0,
      descricao: 'Bônus anual',
      categoria: 'Renda',
      tipo: 'receita',
      status: 'confirmada',
      data_transacao: new Date(),
      data_pagamento: new Date(),
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      user_id: USER_IDS[1],
      valor: 500.0,
      descricao: 'Aluguel',
      categoria: 'Moradia',
      tipo: 'despesa',
      status: 'confirmada',
      data_transacao: new Date(),
      data_pagamento: new Date(),
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      user_id: USER_IDS[2],
      valor: 2000.0,
      descricao: 'Freelance - Projeto Web',
      categoria: 'Renda',
      tipo: 'receita',
      status: 'pendente',
      data_transacao: new Date(),
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      user_id: USER_IDS[2],
      valor: 150.0,
      descricao: 'Compras no supermercado',
      categoria: 'Alimentação',
      tipo: 'despesa',
      status: 'confirmada',
      data_transacao: new Date(),
      data_pagamento: new Date(),
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      user_id: USER_IDS[3],
      valor: 1200.0,
      descricao: 'Salário mensal',
      categoria: 'Renda',
      tipo: 'receita',
      status: 'confirmada',
      data_transacao: new Date(),
      data_pagamento: new Date(),
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      user_id: USER_IDS[4],
      valor: 5000.0,
      descricao: 'Venda de equipamento',
      categoria: 'Vendas',
      tipo: 'receita',
      status: 'confirmada',
      data_transacao: new Date(),
      data_pagamento: new Date(),
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
    {
      id: uuidv4(),
      user_id: USER_IDS[4],
      valor: 1000.0,
      descricao: 'Investimento em ações',
      categoria: 'Investimentos',
      tipo: 'despesa',
      status: 'pendente',
      data_transacao: new Date(),
      is_deleted: false,
      created: new Date(),
      updated: new Date(),
      deleted: null,
    },
  ]);
}

